### ISSUE TITLE
Can't activate the plugin

### ISSUE THREAD

**Issue by gnfisher** [AlbertExtensions/Github-Jump#1]
First of all, thank you for open sourcing this! Second of all, my issue may be (probably is) due to my ignorance of albert.

That said, I am unable to get this plugin to activate. I see the following when i go to activate it:

![image](https://user-images.githubusercontent.com/4742306/108601706-eaa04900-736b-11eb-8c65-fc3a625e575f.png)

I do not see any additional deps required, etc when I hover over it, either.

I am running fedora workstation 33 and gnome 3.38.4.

**Comment by BharatKalluri** [comment]
Hi,
Apologies for not getting back earlier. 
Looks like albert released a new version of their python API, which was not backwards compatible. So, I need to update all the extensions here..

Although the code changes are done, there is currently a blocker which is preventing me from merging. You can follow developments @ https://github.com/AlbertExtensions/Github-Jump/pull/2
